PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS Categoria (Id INTEGER PRIMARY KEY AUTOINCREMENT, Nombre TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Sucursal (Id INTEGER PRIMARY KEY AUTOINCREMENT, Nombre TEXT NOT NULL, Codigo TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Pelicula (Id INTEGER PRIMARY KEY AUTOINCREMENT, Nombre TEXT NOT NULL, CategoriaId INTEGER, FOREIGN KEY (CategoriaId) REFERENCES Categoria(Id));
CREATE TABLE IF NOT EXISTS Sala (Id INTEGER PRIMARY KEY AUTOINCREMENT, NumeroSala INTEGER, Capacidad INTEGER, Clase TEXT, SucursalId INTEGER, FOREIGN KEY (SucursalId) REFERENCES Sucursal(Id));
CREATE TABLE IF NOT EXISTS Funcion (Id INTEGER PRIMARY KEY AUTOINCREMENT, SucursalId INTEGER, SalaId INTEGER, PeliculaId INTEGER, Horario TEXT, FOREIGN KEY (SucursalId) REFERENCES Sucursal(Id), FOREIGN KEY (SalaId) REFERENCES Sala(Id), FOREIGN KEY (PeliculaId) REFERENCES Pelicula(Id));
CREATE TABLE IF NOT EXISTS Usuario (Id INTEGER PRIMARY KEY AUTOINCREMENT, TipoDocumento TEXT, NumeroDocumento TEXT, Nombre TEXT, Apellido TEXT, Correo TEXT);
